gdb-4.14+gdb-4.14-testsuite

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -26,29 +26,33 @@
 #
 host_libs="mmalloc libiberty opcodes bfd readline gash tcl tk tclX"
 
+if [ "${enable_gdbgui}" = "yes" ] ; then
+	host_libs="${host_libs} libgui"
+fi
+
 # these tools are built for the host environment
 #
 host_tools="byacc flex bison binutils ld gas gcc gdb make patch
 	    prms send-pr gprof gdbtest tgas etc expect dejagnu sim
             m4 autoconf ispell grep diff rcs cvs fileutils shellutils
-	    textutils wdiff find emacs uudecode hello tar gzip indent
+	    textutils wdiff find emacs emacs19 uudecode hello tar gzip indent
 	    recode release sed utils"
 
 
 # these libraries are built for the target environment, and are built after
 # the host libraries and the host tools (which may be a cross compiler)
 #
-target_libs="libm xiberty newlib libio libg++"
+target_libs="libm xiberty libgloss newlib libio librx libstdc++ libg++"
 
 
 # these tools are built using the target libs, and are intended to run only
-# in the target environment.  we currently have none.
+# in the target environment
 #
 # note: any program that *uses* libraries that are in the "target_libs"
 # list belongs in this list.  those programs are also very likely
 # candidates for the "native_only" list which follows
 #
-target_tools="groff"
+target_tools="examples groff"
 
 ################################################################################
 
@@ -60,13 +64,13 @@ target_tools="groff"
 
 # directories to be built in the native environment only
 #
-native_only="autoconf cvs emacs fileutils find grep groff gzip hello indent
-             ispell m4 rcs recode sed shellutils tar textutils gash tk uudecode wdiff 
-	     gprof"
+native_only="autoconf cvs emacs emacs19 fileutils find grep groff gzip hello
+	     indent ispell m4 rcs recode sed shellutils tar textutils gash
+	     uudecode wdiff gprof"
 
 # directories to be built in a cross environment only
 #
-cross_only="xiberty newlib"
+cross_only="xiberty libgloss newlib"
 
 ## All tools belong in one of the four categories, and are assigned above
 ## We assign ${configdirs} this way to remove all embedded newlines.  This
@@ -99,14 +103,14 @@ case "${host}" in
   mips*-sgi-irix3*)       host_makefile_frag=config/mh-sysv ;;
   mips*-*-sysv4*)	  host_makefile_frag=config/mh-sysv4 ;;
   mips*-*-sysv*)	  host_makefile_frag=config/mh-riscos ;;
-  i[34]86-ncr-sysv43)     host_makefile_frag=config/mh-ncrsvr43 ;;
-  i[34]86-ncr-sysv4*)     host_makefile_frag=config/mh-ncr3000 ;;
-  i[34]86-*-sco*)         host_makefile_frag=config/mh-sco ;;
-  i[34]86-*-isc*)	  host_makefile_frag=config/mh-sysv ;;
-  i[34]86-*-linux*)       host_makefile_frag=config/mh-linux ;;
-  i[34]86-*-solaris2*)    host_makefile_frag=config/mh-sysv4 ;;
-  i[34]86-*-aix*)	  host_makefile_frag=config/mh-aix386 ;;
-  i[34]86-*-go32*)	  host_makefile_frag=config/mh-go32 ;;
+  i[345]86-ncr-sysv4.3)   host_makefile_frag=config/mh-ncrsvr43 ;;
+  i[345]86-ncr-sysv4*)    host_makefile_frag=config/mh-ncr3000 ;;
+  i[345]86-*-sco*)        host_makefile_frag=config/mh-sco ;;
+  i[345]86-*-isc*)	  host_makefile_frag=config/mh-sysv ;;
+  i[345]86-*-linux*)      host_makefile_frag=config/mh-linux ;;
+  i[345]86-*-solaris2*)   host_makefile_frag=config/mh-sysv4 ;;
+  i[345]86-*-aix*)	  host_makefile_frag=config/mh-aix386 ;;
+  i[345]86-*-go32*)	  host_makefile_frag=config/mh-go32 ;;
   vax-*-ultrix2*)         host_makefile_frag=config/mh-vaxult2 ;;
   *-ibm-aix*)             host_makefile_frag=config/mh-aix ;;
   *-bull-bosx*)           host_makefile_frag=config/mh-aix ;;
@@ -120,6 +124,57 @@ case "${host}" in
   *-*-sysv4*)             host_makefile_frag=config/mh-sysv4 ;;
   *-*-sysv*)              host_makefile_frag=config/mh-sysv ;;
 esac
+fi
+
+# The Solaris /usr/ucb/cc compiler does not appear to work.
+case "${host}" in
+  sparc-sun-solaris2*)
+      if [ "`/usr/bin/which ${CC-cc}`" = "/usr/ucb/cc" ] ; then
+          could_use=
+          [ -d /opt/SUNWspro/bin ] && could_use="/opt/SUNWspro/bin"
+          if [ -d /opt/cygnus/bin ] ; then
+              if [ "$could_use" == "" ] ; then
+                  could_use="/opt/cygnus/bin"
+              else
+                  could_use="$could_use or /opt/cygnus/bin"
+              fi
+          fi
+        if [ "$could_use" = "" ] ; then
+            echo "Warning: compilation may fail because you're using"
+            echo "/usr/ucb/cc.  You should change your PATH or CC "
+            echo "variable and rerun configure."
+        else
+            echo "Warning: compilation may fail because you're using"
+            echo "/usr/ucb/cc, when you should use the C compiler from"
+            echo "$could_use.  You should change your"
+            echo "PATH or CC variable and rerun configure."
+        fi
+      fi
+  ;;
+esac
+
+# We default to --with-shared on platforms where -fpic is meaningless.
+# Well, we don't yet, but we will.
+if false && [ "${host}" = "${target}" ] && [ x${enable_shared} = x ]; then
+  case "${target}" in
+    alpha-dec-osf*)	enable_shared=yes ;;
+    mips-sgi-irix5*)	enable_shared=yes ;;
+    *)			enable_shared=no ;;
+  esac
+fi
+
+if [ x${enable_shared} = xyes ]; then
+  waugh=
+  case "${host}" in
+    hppa*-*-*)		waugh=config/mh-papic ;;
+    i[345]86-*-*)	waugh=config/mh-x86pic ;;
+    *-*-*)		waugh=config/mh-${host_cpu}pic ;;
+  esac
+  if [ -n "${host_makefile_frag}" ] && [ -f ${srcdir}/${waugh} ]; then
+    cat ${srcdir}/${host_makefile_frag} > mh-frag
+    cat ${srcdir}/${waugh} >> mh-frag
+    host_makefile_frag=mh-frag
+  fi
 fi
 
 # per-target:
@@ -146,8 +201,6 @@ case ${with_x} in
     	;;
 esac
 
-
-
 # Some tools are only suitable for building in a "native" situation.
 # Those are added when we have a host==target configuration.  For cross
 # toolchains, we add some directories that should only be useful in a
@@ -171,10 +224,88 @@ else
 	is_cross_compiler=yes
 fi	
 
+copy_dirs=
+
+# Handle --with-headers=XXX.  The contents of the named directory are
+# copied to $(tooldir)/include.
+if [ x"${with_headers}" != x ]; then
+  if [ x${is_cross_compiler} = xno ]; then
+    echo 1>&2 '***' --with-headers is only supported when cross compiling
+    exit 1
+  fi
+  case "${exec_prefixoption}" in
+  "") x=${prefix} ;;
+  *) x=${exec_prefix} ;;
+  esac
+  copy_dirs="${copy_dirs} ${with_headers} $x/${target_alias}/include"
+fi
+
+# Handle --with-libs=XXX.  Multiple directories are permitted.  The
+# contents are copied to $(tooldir)/lib.
+if [ x"${with_libs}" != x ]; then
+  if [ x${is_cross_compiler} = xno ]; then
+    echo 1>&2 '***' --with-libs is only supported when cross compiling
+    exit 1
+  fi
+  # Copy the libraries in reverse order, so that files in the first named
+  # library override files in subsequent libraries.
+  case "${exec_prefixoption}" in
+  "") x=${prefix} ;;
+  *) x=${exec_prefix} ;;
+  esac
+  for l in ${with_libs}; do
+    copy_dirs="$l $x/${target_alias}/lib ${copy_dirs}"
+  done
+fi
+
+# If both --with-headers and --with-libs are specified, default to
+# --without-newlib.
+if [ x"${with_headers}" != x ] && [ x"${with_libs}" != x ]; then
+  if [ x"${with_newlib}" = x ]; then
+    with_newlib=no
+  fi
+fi
+
+# Recognize --without-newlib.
+if [ x${with_newlib} = xno ]; then
+  configdirs=`echo " ${configdirs} " | sed -e 's/ newlib / /'`
+fi
+
+# Handle ${copy_dirs}
+set fnord ${copy_dirs}
+shift
+while [ $# != 0 ]; do
+  if [ -f $2/COPIED ] && [ x"`cat $2/COPIED`" = x"$1" ]; then
+    :
+  else
+    echo Copying $1 to $2
+
+    # Use the install script to create the directory and all required
+    # parent directories.
+    if [ -d $2 ]; then
+      :
+    else
+      echo >config.temp
+      ${srcdir}/install.sh -c -m 644 config.temp $2/COPIED
+    fi
+
+    # Copy the directory, assuming we have tar.
+    # FIXME: Should we use B in the second tar?  Not all systems support it.
+    (cd $1; tar -cf - .) | (cd $2; tar -xpf -)
+
+    # It is the responsibility of the user to correctly adjust all
+    # symlinks.  If somebody can figure out how to handle them correctly
+    # here, feel free to add the code.
+
+    echo $1 > $2/COPIED
+  fi
+  shift; shift
+done
+
 # Configure extra directories which are host specific
 
 case "${host}" in
-  i[34]86-*-go32*)
+  i[345]86-*-go32*)
 		  configdirs="$configdirs dosrel" ;;
 esac
 
@@ -185,31 +316,38 @@ esac
 noconfigdirs=""
 
 case "${host}" in
-  i[34]86-*-netbsd*)
+  i[345]86-*-netbsd*)
     noconfigdirs="tk fileutils"
     ;;
-  i[34]86-*-vsta)
+  i[345]86-*-vsta)
     noconfigdirs="tcl expect dejagnu make texinfo bison patch flex byacc send-pr gprof uudecode dejagnu diff"
     ;;
-  i[34]86-*-go32)
+  i[345]86-*-go32)
     noconfigdirs="tcl expect deja-gnu make texinfo bison patch flex byacc send-pr gprof uudecode dejagnu diff"
     ;;
 esac
 
 
-
-
-
 case "${target}" in
-  alpha-dec-osf1*)
-    noconfigdirs="$noconfigdirs emacs fileutils grep newlib"
-    ;;	
+  *-*-netware)
+    noconfigdirs="$noconfigdirs libg++ libstdc++ librx newlib xiberty"
+    ;;
+  alpha-dec-osf*)
+    # ld works, but does not support shared libraries.  emacs doesn't
+    # work.  newlib is not 64 bit ready.  I'm not sure about emacs19,
+    # fileutils or grep.
+    noconfigdirs="$noconfigdirs ld emacs emacs19 fileutils grep newlib"
+    ;;
   alpha*-*-*)
+    # newlib is not 64 bit ready
     noconfigdirs="$noconfigdirs newlib"
-    ;;    
+    ;;
+  arm-*-*)
+    noconfigdirs="$noconfigdirs ld"
+    ;;
   h8300*-*-* | \
   h8500-*-*)
-    noconfigdirs="$noconfigdirs libg++ libio"
+    noconfigdirs="$noconfigdirs libg++ libstdc++ libio librx"
     ;;
   hppa*-*-*elf*)
     # Do configure ld/binutils/gas for this case.
@@ -217,36 +355,36 @@ case "${target}" in
   hppa*-*-*)
     # HP's C compiler doesn't handle Emacs correctly (but on BSD and Mach
     # cc is gcc, and on any system a user should be able to link cc to
-    # whatever they want.  FIXME, emacs).
+    # whatever they want.  FIXME, emacs emacs19).
     case "${CC}" in
-	"" | cc*) noconfigdirs="$noconfigdirs emacs" ;;
+	"" | cc*) noconfigdirs="$noconfigdirs emacs emacs19" ;;
         *) ;;
     esac
     noconfigdirs="$noconfigdirs ld shellutils"
     ;;
-  i[34]86-*-go32)
+  i[345]86-*-go32)
     # add the go32 support tools to the list
     # but don't build gdb
     configdirs=`echo go32 ${configdirs}`
-    noconfigdirs="$noconfigdirs gdb libg++ libio"
+    noconfigdirs="$noconfigdirs gdb libg++ libstdc++ libio librx"
     ;;
-  i[34]86-*-sco*)
+  i[345]86-*-sco*)
     noconfigdirs="$noconfigdirs gprof"
     ;;
-  i[34]86-*-solaris2*)
+  i[345]86-*-solaris2*)
     # The linker does static linking correctly, but the Solaris C library
     # has bugs such that some important functions won't work when statically
     # linked.  (See man pages for getpwuid, for example.)
     noconfigdirs="$noconfigdirs ld"
     ;;
-  i[34]86-*-sysv4*)
+  i[345]86-*-sysv4*)
     # The SYSV4 C compiler doesn't handle Emacs correctly
     case "${CC}" in
-	"" | cc*) noconfigdirs="$noconfigdirs emacs" ;;
+	"" | cc*) noconfigdirs="$noconfigdirs emacs emacs19" ;;
         *) ;;
     esac
     # but that's okay since emacs doesn't work anyway
-    noconfigdirs="$noconfigdirs emacs"
+    noconfigdirs="$noconfigdirs emacs emacs19"
     ;;
   powerpc-*-aix*)
     # copied from rs6000-*-* entry
@@ -262,14 +400,15 @@ case "${target}" in
     ;;
   rs6000-*-*)
     # a gcc built textutils will cause the linker to hang on 'join'
-    noconfigdirs="$noconfigdirs ld binutils gprof textutils"
+    noconfigdirs="$noconfigdirs gas ld binutils gprof textutils"
     ;;
   m68k-apollo-*)
     noconfigdirs="$noconfigdirs ld binutils gprof"
     ;;
   mips*-*-irix5*)
     # The GNU linker does not support shared libraries.
-    noconfigdirs="$noconfigdirs ld gprof"
+    # emacs is emacs 18, which does not work on Irix 5 (emacs19 does work)
+    noconfigdirs="$noconfigdirs ld gprof emacs"
     ;;
   mips*-dec-bsd*)
     noconfigdirs="$noconfigdirs gprof"
@@ -285,9 +424,9 @@ case "${target}" in
     ;;
   sh-*-*)
     case "${host}" in
-      i[34]86-*-vsta) ;; # don't add gprof back in
+      i[345]86-*-vsta) ;; # don't add gprof back in
       *) configdirs=`echo gprof ${configdirs}` ;;
-      i[34]86-*-go32) ;; # don't add gprof back in
+      i[345]86-*-go32) ;; # don't add gprof back in
       *) configdirs=`echo gprof ${configdirs}` ;;
     esac
     ;;
@@ -310,9 +449,11 @@ case "${target}" in
      ;;    
 esac
 
+# Remove the entries in $noconfigdirs from $configdirs.  If we have the
+# source for them, add them to $notsupp.
 notsupp=""
 for dir in . $noconfigdirs ; do
-  if [ $dir != . ] && echo "# ${configdirs} #" | grep "${dir} " >/dev/null 2>&1 ; then
+  if [ $dir != . ]  && echo " ${configdirs} " | grep " ${dir} " >/dev/null 2>&1; then
     configdirs=`echo " ${configdirs} " | sed -e "s/ ${dir} / /"`
     if [ -r $srcdir/$dir/configure ] || [ -r $srcdir/$dir/configure.in ]; then
       notsupp="$notsupp $dir"
@@ -332,7 +473,7 @@ if [ -n "${notsupp}" ] && [ -z "${norecursion}" ]; then
   # pretend that all is well.)
   if [ -n "$appdirs" ]; then
     for dir in $appdirs ; do
-      if [ -r $dir/Makefile.in ] && echo "# ${configdirs} #" | grep "${dir} " >/dev/null 2>&1 ; then
+      if [ -r $dir/Makefile.in ] && echo " ${configdirs} " | grep " ${dir} " >/dev/null 2>&1 ; then
 	appdirs=""
 	break
       fi
@@ -374,6 +515,14 @@ if [ x${use_gnu_ld} = x ] ; then
     with_gnu_ld=yes
     withoptions="$withoptions --with-gnu-ld"
   fi
+fi
+
+if [ x${enable_shared} = xyes ]; then
+  case "${target}" in
+    hppa*-*-*)		target_makefile_frag=config/mt-papic ;;
+    i[345]86-*-*)	target_makefile_frag=config/mt-x86pic ;;
+    *-*-*)		target_makefile_frag=config/mt-${target_cpu}pic ;;
+  esac
 fi
 
 #
