gdb-4.0.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,7 +24,7 @@ configdirs=
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  */
 
-# $Id: configure,v 1.22 1991/07/20 01:22:30 rich Exp $
+# $Id: configure,v 1.31 1991/08/23 04:50:57 rich Exp $
 
 #
 # Shell script to create proper links to machine-dependent files in
@@ -55,11 +55,13 @@ hostsubdir=
 Makefile=Makefile
 Makefile_in=Makefile.in
 norecurse=
+recursing=
 removing=
 srcdir=
 srctrigger=
 target=
 targets=
+commontargets=
 targetsubdir=
 template=
 verbose=
@@ -67,51 +69,54 @@ verbose=
 for arg in $*;
 do
 	case ${arg} in
-	-ansi | +ansi)
+	-ansi | +a*)
 		ansi=true
+		clib=clib
 		;;
 	-destdir=* | +destdir=* | +destdi=* | +destd=* | +dest=* | +des=* | +de=* | +d=*)
 		destdir=`echo ${arg} | sed 's/[+-]d[a-z]*=//'`
-		;;
-	-forcesubdirs | +forcesubdirs | +forcesubdir | +forcesubdi | +forcesubd \
-	| +forcesub | +forcesu | +forces | +force | +forc | +for | +fo | +f)
-		forcesubdirs=${arg}
 		;;
 	-languages=* | +languages=* | +language=* | +languag=* \
 		| +langua=* | +langu=* | +lang=* | +lan=* | +la=* \
 		| +l=*)
 		languages="${languages} `echo ${arg} | sed 's/[+-]l[a-z]*=//'`"
 		;;
-	-gas | +gas | +ga | +g)
+	-gas | +g*)
 		gas=yes
 		;;
-	-help | +h | +help)
+	-help | +h*)
 		fatal=true
 		;;
-	-nfp | +nfp | +nf | +n)
+	-nfp | +nf*)
 		nfp=yes
 		;;
-	-norecurse | +norecurse)
+	-norecurse | +no*)
 		norecurse=true
 		;;
-	-rm | +rm)
+	-recursing)
+		recursing=true
+		;;
+	-rm | +r*)
 		removing=${arg}
 		;;
 #	-srcdir=* | +srcdir=* | +srcdi=* | +srcd=* | +src=* | +sr=* | +s=*)
 #		srcdir=`echo ${arg} | sed 's/[+-]s[a-z]*=//'`
 #		;;
-	-target=* | +target=* | +targe=* | +targ=* | +tar=* | +ta=* | +t=*)
+	-subdirs | +f* | +su*)
+		subdirs=${arg}
+		;;
+	-target=* | +target=* | +targe=* | +targ=* | +tar=* | +ta=*)
 		if [ -n "${targets}" ] ; then
-			forcesubdirs="+forcesubdirs"
+			subdirs="+subdirs"
 		fi
 
 		newtargets="${targets} `echo ${arg} | sed 's/[+-]t[a-z]*=//'`"
 		targets="${newtargets}"
 		;;
-	-template=* | +template=*)
+	-template=* | +template=* | +templat=* | +templa=* | +templ=* | +temp=* | +tem=* | +te=*)
 		template=`echo ${arg} | sed 's/[+-]template=//'`
 		;;
-	+verbose | +verbos | +verbo | +verb | +ver | +ve | +v)
+	-v | -verbose | +v*)
 		verbose=${arg}
 		;;
 	-* | +*)
@@ -122,7 +127,7 @@ do
 		;;
 	*)
 		if [ -n "${hosts}" ] ; then
-			forcesubdirs="+forcesubdirs"
+			subdirs="+subdirs"
 		fi
 
 		newhosts="${hosts} ${arg}"
@@ -133,7 +138,6 @@ done
 
 if [ -n "${verbose}" ] ; then
 	echo `pwd`/configure $*
-	echo targets=\"${targets}\"
 fi
 
 # process host and target only if not rebuilding configure itself or removing.
@@ -142,7 +146,7 @@ if [ -z "${template}" -a -z "${removing}" -a -z "${fatal}" ] ; then
 	if [ -z "${hosts}" ] ; then
 		(echo ;
 		echo "configure: No HOST specified." ;
-		echo) 2>&1
+		echo) 1>&2
 		fatal=true
 	fi
 fi
@@ -153,7 +157,7 @@ if [ -n "${fatal}" -o "${hosts}" = "help" ] ; then
 	echo "Options: [defaults in brackets]" ;
 	echo " +ansi		configure w/ANSI library. [no ansi lib]" ;
 	echo " +destdir=MYDIR	configure for installation into MYDIR. [/usr/local]" ;
-	echo " +forcesubdirs	configure in subdirectories.  [in source directories]" ;
+	echo " +subdirs		configure in subdirectories.  [in source directories]" ;
 	echo " +lang=LANG	configure to build LANG. [gcc]" ;
 	echo " +help		print this message. [normal config]" ;
 	echo " +gas		configure the compilers for use with gas. [native as]" ;
@@ -164,7 +168,7 @@ if [ -n "${fatal}" -o "${hosts}" = "help" ] ; then
 	echo " +template=TEM	rebuild configure using TEM. [normal config]" ;
 	echo ;
 	echo "Where HOST and TARGET are something like \"vax\", \"sun3\", \"encore\", etc." ;
-	echo "Asking for more than one \"+target\" implies \"+forcesubdirs\".  Any other" ;
+	echo "Asking for more than one \"+target\" implies \"+subdirs\".  Any other" ;
 	echo "options given will apply to all targets.") 1>&2
 
 	if [ -r config.status ] ; then
@@ -175,15 +179,21 @@ if [ -n "${fatal}" -o "${hosts}" = "help" ] ; then
 fi
 
 #### configure.in common parts come in here.
-srcname="GDB"
-srctrigger=main.c
+# This file is a shell script fragment that supplies the information
+# necessary to tailor a template configure script into the configure
+# script appropriate for this directory.  For more information, check
+# any existing configure script.
+
+configdirs="libiberty bfd binutils bison gcc readline ld gas gnulib ${clib} gdb make prms "
+srctrigger=README.configure
+srcname="gnu development package"
 
 ## end of common part.
 
 # are we rebuilding config itself?
 if [ -n "${template}" ] ; then
 	if [ ! -r ${template} ] ; then
-		echo "Can't find template ${template}."
+		echo '***' "Can't find template ${template}." 1>&2
 		exit 1
 	fi
 
@@ -204,12 +214,12 @@ if [ -n "${template}" ] ; then
 
 	if [ -r configure.in ] ; then
 		if [ -z "`grep '^# per\-host:' configure.in`" ] ; then
-			echo `pwd`/configure.in has no "per-host:" line.
+			echo '***' `pwd`/configure.in has no "per-host:" line. 1>&2
 			exit 1
 		fi
 
 		if [ -z "`grep '^# per\-target:' configure.in`" ] ; then
-			echo `pwd`/configure.in has no "per-target:" line.
+			echo '***' `pwd`/configure.in has no "per-target:" line. 1>&2
 			exit 1
 		fi
 
@@ -242,7 +252,21 @@ if [ -n "${template}" ] ; then
 	rm template.new
 #	mv configure configure.old
 	mv configure.new configure
-	echo Rebuilt configure in `pwd`
+
+	if [ -n "${verbose}" ] ; then
+		echo Rebuilt configure in `pwd`
+	fi
+
+	# Now update config.sub from the template directory.
+	if echo "$template" | grep -s 'configure$' ; then
+		cp `echo "$template" | sed s/configure$/config.sub/` ./config.sub.new
+	#	mv config.sub config.sub.old
+		mv config.sub.new config.sub
+
+		if [ -n "${verbose}" ] ; then
+			echo Rebuilt config.sub in `pwd`
+		fi
+	fi
 
 	if [ -z "${norecurse}" ] ; then
 		# If template is relative path, make it absolute for recursing.
@@ -268,10 +292,12 @@ if [ -n "${template}" ] ; then
 						(cd $i ;
 							./configure +template=${template} ${verbose})
 					else
-						echo No configure script in `pwd`/$i
+						echo Warning: No configure script in `pwd`/$i
 					fi
 				else
-					echo Warning: directory $i is missing.
+					if [ -n "${verbose}" ] ; then
+					  echo Warning: directory $i is missing.
+					fi
 				fi
 			done
 		done
@@ -282,7 +308,7 @@ fi
 
 # some sanity checks on configure.in
 if [ -z "${srctrigger}" ] ; then
-	echo srctrigger not set in configure.in. `pwd` not configured.
+	echo Warning: srctrigger not set in configure.in. `pwd` not configured.
 	exit 1
 fi
 
@@ -293,64 +319,27 @@ for host in ${hosts} ; do
 		defaulttargets=true
 	fi
 
+	result=`/bin/sh ./config.sub ${host}`
+	host_cpu=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
+	host_vendor=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
+	host_os=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
+	host=${host_cpu}-${host_vendor}-${host_os}
 	host_makefile_frag=config/hmake-${host}
 
 #### configure.in per-host parts come in here.
 
-if [ ! -f xconfig/${host} ]; then
-	echo "No such host ${host}"
-	exit 1
-fi
-
-#  We really shouldn't depend on there being a space after XM_FILE= ...
-hostfile=`awk '$1 == "XM_FILE=" { print $2 }' <xconfig/$host`
-
 ## end of per-host part.
-
 
 	for target in ${targets} ; do
 
-		if [ -n "${verbose}" ] ; then
-			echo "	target=\"${target}\""
-		fi
-
+		result=`/bin/sh ./config.sub ${target}`
+		target_cpu=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\1/'`
+		target_vendor=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\2/'`
+		target_os=`echo $result | sed 's/^\(.*\)-\(.*\)-\(.*\)$/\3/'`
+		target=${target_cpu}-${target_vendor}-${target_os}
 		target_makefile_frag=config/tmake-${target}
 
 #### configure.in per-target parts come in here.
-
-if [ ! -f tconfig/${target} ]; then
-	echo "No such target ${target}"
-	exit 1
-fi
-
-if [ -z "${removing}" ] ; then
-	cat xconfig/${host} tconfig/${target} | awk '$1 == "#msg" {
-		print substr($0,6)}'
-fi
-
-#  We really shouldn't depend on there being a space after TM_FILE= ...
-targetfile=`awk '$1 == "TM_FILE=" { print $2 }' <tconfig/$target`
-
-host_makefile_frag=xconfig/${host}
-target_makefile_frag=tconfig/${target}
-
-# If hostfile (XM_FILE) and/or targetfile (TM_FILE) is not set in the
-# ?config/* file, we don't make the corresponding links.  But we have
-# to remove the xm.h files and tm.h files anyway, e.g. when switching
-# from "configure host" to "configure none".
-files=
-links=
-rm -f xm.h
-if [ "${hostfile}" != "" ]; then
-	files="${files} ${hostfile}"
-	links="${links} xm.h"
-fi
-rm -f tm.h
-if [ "${targetfile}" != "" ]; then
-	files="${files} ${targetfile}"
-	links="${links} tm.h"
-fi
-
 ## end of per-target part.
 
 		# Temporarily, we support only direct subdir builds.
@@ -358,11 +347,11 @@ fi
 		targetsubdir=Target-${target}
 
 		if [ -n "${removing}" ] ; then
-			if [ -n "${forcesubdirs}" ] ; then
+			if [ -n "${subdirs}" ] ; then
 				if [ -d "${hostsubdir}" ] ; then
 					rm -rf ${hostsubdir}/${targetsubdir}
 
-					if [ -z "`(ls ${hostsubdir}) 2>&1 | grep Target-`" ] ; then
+					if [ -z "`(ls ${hostsubdir}) 2>&1 | grep Target- | grep -v Target-independent`" ] ; then
 						rm -rf ${hostsubdir}
 					fi
 				else
@@ -372,24 +361,35 @@ fi
 				rm -f ${Makefile} config.status ${links}
 			fi
 		else
-			if [ -n "${forcesubdirs}" ] ; then
+			if [ -n "${subdirs}" ] ; then
 				# check for existing status before allowing forced subdirs.
 				if [ -f ${Makefile} ] ; then
-					echo "${Makefile} already exists in source directory.  `pwd` not configured."
+					echo '***' "${Makefile} already exists in source directory.  `pwd` not configured." 1>&2
 					exit 1
 				fi
 
 				if [ ! -d ${hostsubdir} ] ; then mkdir ${hostsubdir} ; fi
 				cd ${hostsubdir}
 
-				if [ ! -d ${targetsubdir} ] ; then mkdir ${targetsubdir} ; fi
+				if [ ! -d ${targetsubdir} ] ; then
+					if [ -z "${commontargets}" ] ; then
+						mkdir ${targetsubdir}
+					else
+						if [ ! -d Target-independent ] ; then
+							mkdir Target-independent
+						fi
+
+						${symbolic_link} Target-independent ${targetsubdir}
+					fi # if target independent
+				fi # if no target dir yet
+
 				cd ${targetsubdir}
 
 				srcdir=../..
 			else
 				# if not subdir builds, then make sure none exist.
 				if [ -n "`(ls .) 2>&1 | grep Host-`" ] ; then
-					echo "Configured subdirs exist.  `pwd` not configured."
+					echo '***' "Configured subdirs exist.  `pwd` not configured." 1>&2
 					exit 1
 				fi
 			fi
@@ -405,12 +405,12 @@ fi
 
 			if [ -n "${srctrigger}" -a ! -r ${srcdir}/${srctrigger} ] ; then
 				if [ -z "${srcdirdefaulted}" ] ; then
-					echo "${progname}: Can't find ${srcname} sources in `pwd`/${srcdir}" 1>&2
+					echo '***' "${progname}: Can't find ${srcname} sources in `pwd`/${srcdir}" 1>&2
 				else
-					echo "${progname}: Can't find ${srcname} sources in `pwd`/. or `pwd`/.." 1>&2
+					echo '***' "${progname}: Can't find ${srcname} sources in `pwd`/. or `pwd`/.." 1>&2
 				fi
 
-				echo \(At least ${srctrigger} is missing.\) 1>&2
+				echo '***' \(At least ${srctrigger} is missing.\) 1>&2
 				exit 1
 			fi
 
@@ -424,8 +424,8 @@ fi
 				set ${links}; link=$1; shift; links=$*
 
 				if [ ! -r ${srcdir}/${file} ] ; then
-					echo "${progname}: cannot create a link \"${link}\"," 1>&2
-					echo "since the file \"${file}\" does not exist." 1>&2
+					echo '***' "${progname}: cannot create a link \"${link}\"," 1>&2
+					echo '***' "since the file \"${file}\" does not exist." 1>&2
 					exit 1
 				fi
 
@@ -435,10 +435,13 @@ fi
 				${symbolic_link} ${srcdir}/${file} ${link} 2>/dev/null || ${hard_link} ${srcdir}/${file} ${link}
 
 				if [ ! -r ${link} ] ; then
-					echo "${progname}: unable to link \"${link}\" to \"${srcdir}/${file}\"." 1>&2
+					echo '***' "${progname}: unable to link \"${link}\" to \"${srcdir}/${file}\"." 1>&2
 					exit 1
 				fi
-				echo "Linked \"${link}\" to \"${srcdir}/${file}\"."
+
+				if [ -n "${verbose}" ] ; then
+					echo "Linked \"${link}\" to \"${srcdir}/${file}\"."
+				fi
 			done
 
 			# Create a .gdbinit file which runs the one in srcdir
@@ -474,7 +477,7 @@ fi
 			echo "host = ${host}" >> ${Makefile}
 			echo "target = ${target}" >> ${Makefile}
 
-			if [ -n "${forcesubdirs}" ] ; then
+			if [ -n "${subdirs}" ] ; then
 				echo "subdir = /${hostsubdir}/${targetsubdir}" >> ${Makefile}
 			else
 				echo "subdir =" >> ${Makefile}
@@ -531,19 +534,12 @@ fi
 				andusing=${using}
 			fi
 
-			echo "Created \"${Makefile}\"" in `pwd`${andusing}.
+			if [ -n "${verbose}" -o -z "${recursing}" ] ; then
+				echo "Created \"${Makefile}\"" in `pwd`${andusing}.
+			fi
 
 #### configure.in post-target parts come in here.
 
-case ${srcdir} in
-  .)
-    ;;
-  *)
-    grep -s "source ${srcdir}/.gdbinit" .gdbinit 2>/dev/null || \
-      echo "source ${srcdir}/.gdbinit" >> .gdbinit
-esac
-
-cat ${srcdir}/alldeps.mak ${srcdir}/depend >>Makefile
 ## end of post-target part.
 
 			if [ "${host}" = "${target}" ] ; then
@@ -559,107 +555,80 @@ cat ${srcdir}/alldeps.mak ${srcdir}/depend >>Makefile
 			originaldir=`pwd`
 			cd ${srcdir}
 		fi
+
+		# If there are subdirectories, then recurse. 
+		if [ -z "${norecurse}" -a -n "${configdirs}" ] ; then 
+			for configdir in ${configdirs} ; do
+				if [ -n "${verbose}" ] ; then
+					echo Configuring ${configdir}...
+				fi
+
+				if [ -d ${configdir} ] ; then
+					(cd ${configdir} ;
+						./configure -recursing ${host} +target=${target} \
+							${verbose} ${subdirs} ${removing} +destdir=${destdir}) \
+						| sed 's/^/	/'
+				else
+					if [ -n "${verbose}" ] ; then
+						echo Warning: directory \"${configdir}\" is missing.
+					fi
+				fi
+			done
+		fi
 	done # for each target
 
-#	# Now build a Makefile for this host.
-#	if [ -n "${forcesubdirs}" ] ; then
-#		cd ${hostsubdir}
-#		cat > GNUmakefile << E!O!F
-## Makefile generated by configure for host ${host}.
-#
-#%:
-#	for i in ${targets} ; do \
-#		$(MAKE) -C Target-\$i \$@
-#
-#all clean stage1 stage2 stage3 stage4etags tags TAGS
-#E!O!F
-#	fi
+	# Now build a Makefile for this host.
+	if [ -n "${subdirs}" -a ! -n "${removing}" ] ; then
+		cd ${hostsubdir}
+		cat > GNUmakefile << E!O!F
+# Makefile generated by configure for host ${host}.
+
+ALL := $(shell ls -d Target-*)
+
+%:
+	$(foreach subdir,$(ALL),$(MAKE) -C $(subdir) \$@ &&) true
+
+all:
+E!O!F
+		cd ..
+	fi
 done # for each host
-
-# If there are subdirectories, then recurse. 
-
-if [ -n "${norecurse}" -o -z "${configdirs}" ] ; then exit 0 ; fi
-
-# configdirs is not null
-for configdir in ${configdirs} ; do
-	echo Configuring ${configdir}...
-	specifics=
-	commons=
-
-	if [ -n "${defaulttargets}" ] ; then
-		for host in ${hosts} ; do
-			if [ -d ${configdir}.${host} ] ; then
-				newspecifics="${specifics} ${host}"
-				specifics=${newspecifics}
-			else
-				newcommons="${commons} ${host}"
-				commons=${newcommons}
-			fi # if target specific
-		done # for each host
-
-		if [ -n "${commons}" ] ; then
-			if [ -d ${configdir} ] ; then
-				(cd ${configdir} ;
-					./configure ${commons} ${verbose} ${forcesubdirs} ${removing} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			else
-				echo Warning: directory \"${configdir}\" is missing.
-			fi
-		fi # if any common hosts
-
-		if [ -n "${specifics}" ] ; then
-			for host in ${specifics} ; do
-				echo Configuring target specific directory ${configdir}.${host}...
-				(cd ${configdir}.${host} ;
-					./configure ${host} ${verbose} ${forcesubdirs} ${removing} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			done # for host in specifics
-		fi # if there are any specifics
-	else
-
-		for target in ${targets} ; do
-			if [ -d ${configdir}.${target} ] ; then
-				newspecifics="${specifics} ${target}"
-				specifics=${newspecifics}
-			else
-				newcommons="${commons} +target=${target}"
-				commons=${newcommons}
-			fi
-
-		done # check for target specific dir override
-
-		if [ -n "${verbose}" ] ; then
-			echo "	"commons=\"${commons}\"
-			echo "	"specifics=\"${specifics}\"
-		fi # if verbose
-
-		if [ -n "${commons}" ] ; then
-			if [ -d ${configdir} ] ; then
-				(cd ${configdir} ;
-					./configure ${hosts} ${verbose} ${forcesubdirs} ${removing} \
-						${commons} +destdir=${destdir}) \
-					| sed 's/^/	/'
-			else
-				echo Warning: directory \"${configdir}\" is missing.
-			fi
-		fi # if any commons
-
-		if [ -n "${specifics}" ] ; then
-			for target in ${specifics} ; do
-				echo Configuring target specific directory ${configdir}.${target}...
-				(cd ${configdir}.${target} ;
-					./configure ${hosts} ${verbose} ${forcesubdirs} ${removing} \
-						"+target=${target}" +destdir=${destdir}) \
-					| sed 's/^/	/'
-			done
-		fi # if any specifics
-	fi # not default targets
-done
 
 exit 0
 
 #
 # $Log: configure,v $
+# Revision 1.31  1991/08/23  04:50:57  rich
+# Minor config polish.
+#
+# Revision 1.22  1991/08/23  03:31:43  rich
+# Minor polish & config mapping.
+#
+# Revision 1.30  1991/08/22  07:15:51  rich
+# Three part names, etc.
+#
+# Revision 1.29  1991/08/20  04:56:51  rich
+# revisiting error messages
+#
+# Revision 1.28  1991/08/16  19:22:17  rich
+# This is the commontargets change and should be considered
+# experimental.
+#
+# Revision 1.27  1991/08/08  01:14:13  rich
+# allow +f to stand in for +subdirs
+#
+# Revision 1.26  1991/08/07  19:21:32  rich
+# +forcesubdirs -> +subdirs
+#
+# Revision 1.25  1991/08/07  07:05:30  rich
+# Added make.
+#
+# Revision 1.24  1991/08/06  19:26:01  rich
+# revised option parsing.
+#
+# Revision 1.23  1991/08/06  19:12:32  rich
+# Host-level GNUmakefiles.
+#
 # Revision 1.22  1991/07/20  01:22:30  rich
 # propogate gdb changes and destdir fix
 #
